server:
  compression:
    enabled: true
    mime-types: application/json,text/plain,text/html
    min-response-size: 1024
spring:
  profiles:
    active: dev  # 默认启用本地环境
  application:
    name: im-server

netty:
  websocket:
    port: 8000
    cluster-id: 1

serializer:
  algorithm: Json

jwt:
  accessToken:
    secret: qwertyuiopasdfghjklzxcvbnmqzzzlew